format = """
$directory\
$git_branch\
$git_status
""""
palette = "catppuccin_mocha"

[directory]
format = '[ $path]($style)[$read_only]($read_only_style) '
style = 'fg:text'
truncation_length = 8

[git_branch]
format = ' [$symbol$branch]($style)'
style = 'fg:blue'

[git_status]
format = '([ \[$all_status$ahead_behind\]]($style))'
style = 'fg:lavender'

[palettes.catppuccin_mocha]
base = "#161616"
blue = "#89b4fa"
crust = "#000000"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#0b0b0b"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6f6f6f"
overlay1 = "#8d8d8d"
overlay2 = "#a8a8a8"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#c6c6c6"
subtext1 = "#e0e0e0"
surface0 = "#262626"
surface1 = "#393939"
surface2 = "#525252"
teal = "#94e2d5"
text = "#f4f4f4"
yellow = "#f9e2af"
